version: 0.0.{build}

cache:
  - vendor/bundle

environment:
  matrix:
    - RUBY_VERSION: 21

install:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - bundle config --local path vendor/bundle
  - bundle install

before_test:
  - ruby -v
  - gem -v
  - bundle -v

build_script:
  - bundle exec rake package

test_script:
  - bundle exec rake -T
